### ISSUE TITLE
Make file in lib folder does not support option python2/python3

### ISSUE THREAD

**Issue by GBJim** [Austriker/py-faster-rcnn#3]
Hi @Austriker 
When I was following your tutorial on README.md, the command in lib folder `make python2/python3`
prompted an error:
make: **\* No rule to make target `python2/python3'.  Stop.

I found that the make file does not contain python2/python3 option

**Comment by Austriker** [comment]
@GBJim I did a shortcut in the readme. I should be either `make python2` or `make python3`

**Comment by GBJim** [comment]
@Austriker:   Ah I see :smile:
